{% set name = "pyopenssl" %}
{% set version = "25.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyOpenSSL/{{ name }}-{{ version }}.tar.gz
  sha256: cd2cef799efa3936bb08e8ccb9433a575722b9dd986023f1cabc4ae64e9dac16

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cryptography >=45.0.7,<47
    - typing_extensions >=4.9  # [py<313]

test:
  imports:
    - OpenSSL
    - OpenSSL.crypto
    - OpenSSL.rand
    - OpenSSL.SSL
  requires:
    - pip
  commands:
    - pip check
    - python -m OpenSSL.debug

about:
  home: https://github.com/pyca/pyopenssl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
  description: |
    pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.
    It includes:
    -SSL.Connection objects, wrapping the methods of Python's portable sockets
    -Callbacks written in Python
    -Extensive error-handling mechanism, mirroring OpenSSL's error codes
    and much more.
  doc_url: https://www.pyopenssl.org/en/latest/
  dev_url: https://github.com/pyca/pyopenssl

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
    - mingwandroid
