travis:
  secure:
    BINSTAR_TOKEN: BX2D1NJWNV3iEsPXrRDkiBHNTv4Awv5BXnJEo8oEJ5nWZXm8BS8oTmSivlBoeh13gNxez++5vT9tWWIRWB8JJneneaedYZ4n/MFhZNZQ1b7/pki0rA59gSbNqfHoYukotyonfXrrT3lHTwRLvGU1s/ZLaoL7MgyAKgVxdcpQ76Wor2Q84eSHxZ83o4U+uBlEjNh1gk4boqQ9wf2A9Gp4uOEj8a4AzTZyfXes+RT8Eko3bgCxNHG/BhYRLxB6SPMn/98DaxIdJbA1DwfNsvzVP9iURjmGiVVajEBem3FaUTHu5rI9qRAd1GKvp3cP9d49J7tqoAixb2ktRKNSKRzj3vSS8G4Me4B2E84WK68IN7Da+GsB41/5baEAbZkZrfHnkBTzLo00wmZ1v0srOLqvx3PaEtsrBpBlaCxZnnOc18q3DkpL+oip9JjiS+KoEM+9eBF5N/hRC8OFzp77sOyUyflWcBQFJrvRcOs9EHWo/yJonuhgRhG9Qz3FwCi8DFSVTzLQtJXMS1127gpbKQ70jmDfE/T4HDXN4MLss5qC/fqcGCLgbXzY5lvHwuVU6J5rEXiMzmTsSA96SBul3SAOt7MgVwF0Jb1HLr6vhB0/NoowOLytn6m/yzrum3P31/tdMrVPQWuPtuYV/P/p3c2BAGJKfm9ZbcXkbXsoX2x4u78=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
